import tkinter as tk
from PIL import Image,ImageTk
def maiin():
    universe = tk.Tk()
    universe.geometry('360x500')
    label4 = tk.Label(universe, text="Kosmos")
    label4.place(x=100, y=190)
    ent5 = tk.Entry(universe)
    ent5.place(x=100, y=230)
    Q = tk.Button(universe, text="Browse")  # , command=login)  #
    Q.place(x=260, y=230)
    universe.mainloop()
def login():
    milkyway = tk.Tk()
    milkyway.geometry('360x500')
    image2 = Image.open("D:/cosmos.png")
    tes = ImageTk.PhotoImage(image2)
    label1 = tk.Label(image=tes)
    label1.image = tes
    label1.place(x=50, y=0)
    label4 = tk.Label(milkyway, text="Kosmos")
    label4.place(x=100, y=190)
    label2 = tk.Label(milkyway, text="User_id")
    label2.place(x=50, y=230)
    ent1=tk.Entry(milkyway,width=120)
    ent1.place(x=190, y=230)
    ent2 = tk.Entry(milkyway, width=120)
    ent2.place(x=190, y=270)
    label3 = tk.Label(milkyway, text="Password")
    label3.place(x=50, y=270)
    R = tk.Button(milkyway, text="Log-in",command=maiin)  # , command=login)  #
    R.place(x=100, y=310)
    milkyway.mainloop()

def sign():
    andromeda = tk.Tk()
    andromeda.geometry('360x500')
    name_1 = tk.StringVar()
    age_1 = tk.StringVar()
    username_1 = tk.StringVar()
    password_1 = tk.StringVar()
    image2 = Image.open("D:/cosmos.png")
    def moon1():
        moonsand1 = tk.Tk()
        moonsand1.geometry('360x500')
        name = name_1.get()
        print(name)
        a=age_1.get()
        b=username_1.get()
        c=password_1.get()
        label4 = tk.Label(moonsand1, text="Kosmos")
        label4.place(x=100, y=190)
        label5 = tk.Label(moonsand1, text=name)
        label5.place(x=100, y=370)
        label6 = tk.Label(moonsand1, text=name)
        label6.place(x=100, y=410)
        label6 = tk.Label(moonsand1, text=name)
        label6.place(x=100, y=450)
        name_1.set("")
        age_1.set("")
        username_1.set("")
        password_1.set("")
        label2 = tk.Label(moonsand1, text="Account Successfully created")
        label2.place(x=100, y=230)
        Q = tk.Button(moonsand1, text="Browse", command=maiin)  # , command=login)  #
        Q.place(x=100, y=270)
        moonsand1.mainloop()
    tes = ImageTk.PhotoImage(image2)
    label1 = tk.Label(image=tes)
    label1.image = tes
    label1.place(x=50, y=0)
    label4 = tk.Label(andromeda, text="Kosmos")
    label4.place(x=100, y=190)
    label2_1 = tk.Label(andromeda, text="Name")
    label2_1.place(x=50, y=230)
    label3 = tk.Label(andromeda, text="Age")
    label3.place(x=50, y=270)
    label2 = tk.Label(andromeda, text="User_id")
    label2.place(x=50, y=310)
    label3 = tk.Label(andromeda, text="Password")
    label3.place(x=50, y=350)
    ent1 = tk.Entry(andromeda, width=120, textvariable=name_1)
    ent1.place(x=190, y=230)
    ent2 = tk.Entry(andromeda, width=120, textvariable=age_1)
    ent2.place(x=190, y=270)
    ent3 = tk.Entry(andromeda, width=120, textvariable=username_1)
    ent3.place(x=190, y=310)
    ent4 = tk.Entry(andromeda, width=120, textvariable=password_1)
    ent4.place(x=190, y=350)
    R = tk.Button(andromeda, text="Sign-up",command=moon1)  # , command=login)  #
    R.place(x=100, y=390)
    andromeda.mainloop()

solar=tk.Tk()
solar.geometry('430x500')
solar.title("Kosmos")
#Milkyway=tkinter.Tk()
#Andromeda=tkinter.Tk()
#Cygnus=tkinter.Tk()
username_2=tk.StringVar()
password_2=tk.StringVar()
image1 = Image.open("D:/cosmos.png")
test = ImageTk.PhotoImage(image1)
label1 = tk.Label(image=test)
label1.image = test
# Position image
label1.place(x=50, y=0)
label2 = tk.Label(solar,text="Kosmos")
label2.place(x=180, y=250)
B = tk.Button(solar, text ="Sign-up",command=sign) #command = helloCallBack)
C = tk.Button(solar, text ="Log-in",command=login)#
B.place(x=180, y=290)
C.place(x=180, y=330)
solar.mainloop()